<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'accessortest' => '/ludoDB/Tests/AccessorTest.php',
                'car' => '/ludoDB/Tests/classes/Car.php',
                'carcollection' => '/ludoDB/Tests/classes/CarCollection.php',
                'carproperties' => '/ludoDB/Tests/classes/CarProperties.php',
                'carproperty' => '/ludoDB/Tests/classes/CarProperty.php',
                'chesstests' => '/Tests/ChessTests.php',
                'city' => '/ludoDB/Tests/classes/City.php',
                'client' => '/ludoDB/Tests/classes/Client.php',
                'collectiontest' => '/ludoDB/Tests/CollectionTest.php',
                'configparsertest' => '/ludoDB/Tests/ConfigParserTest.php',
                'configparsertestjson' => '/ludoDB/Tests/ConfigParserTestJSON.php',
                'country' => '/ludoDB/Tests/classes/Country.php',
                'dbtest' => '/ludoDB/Tests/DBTest.php',
                'fen' => '/Fen.php',
                'fentest' => '/Tests/FenTest.php',
                'findertest' => '/ludoDB/Tests/FinderTest.php',
                'forsqltest' => '/ludoDB/Tests/classes/ForSQLTest.php',
                'game' => '/Game.php',
                'gametest' => '/Tests/GameTest.php',
                'jsontest' => '/ludoDB/Tests/JSONTest.php',
                'ludodb' => '/ludoDB/LudoDB.php',
                'ludodbcollection' => '/ludoDB/LudoDBCollection.php',
                'ludodbconfigparser' => '/ludoDB/LudoDBConfigParser.php',
                'ludodbiterator' => '/ludoDB/LudoDBIterator.php',
                'ludodbobject' => '/ludoDB/LudoDBObject.php',
                'ludodbregistry' => '/ludoDB/LudoDBRegistry.php',
                'ludodbtable' => '/ludoDB/LudoDBTable.php',
                'ludofinder' => '/ludoDB/LudoFinder.php',
                'ludosql' => '/ludoDB/LudoSQL.php',
                'manager' => '/ludoDB/Tests/classes/Manager.php',
                'metadata' => '/Metadata.php',
                'metadatacollection' => '/MetadataCollection.php',
                'metadatatest' => '/Tests/MetadataTest.php',
                'metadatavalue' => '/MetadataValue.php',
                'move' => '/Move.php',
                'moves' => '/Moves.php',
                'person' => '/ludoDB/Tests/classes/Person.php',
                'personforconfigparser' => '/ludoDB/Tests/classes/PersonForConfigParser.php',
                'phone' => '/ludoDB/Tests/classes/Phone.php',
                'phonecollection' => '/ludoDB/Tests/classes/PhoneCollection.php',
                'player' => '/Player.php',
                'playerfinder' => '/PlayerFinder.php',
                'playertest' => '/Tests/PlayerTest.php',
                'seek' => '/Seek.php',
                'seektest' => '/Tests/SeekTest.php',
                'session' => '/Session.php',
                'sessiontest' => '/Tests/SessionTest.php',
                'sqltest' => '/ludoDB/Tests/SQLTest.php',
                'testbase' => '/ludoDB/Tests/TestBase.php',
                'testgame' => '/ludoDB/Tests/classes/TestGame.php',
                'testtable' => '/ludoDB/Tests/classes/TestTable.php',
                'timecontrol' => '/TimeControl.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    }
);
// @codeCoverageIgnoreEnd