<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'car' => '/ludoDB/Tests/Car.php',
                'chesstests' => '/Tests/ChessTests.php',
                'city' => '/ludoDB/Tests/City.php',
                'country' => '/ludoDB/Tests/Country.php',
                'dbtest' => '/ludoDB/Tests/DBTest.php',
                'ludodb' => '/ludoDB/LudoDB.php',
                'ludodbtable' => '/ludoDB/LudoDbTable.php',
                'person' => '/ludoDB/Tests/Person.php',
                'player' => '/Player.php',
                'seek' => '/Seek.php',
                'seektest' => '/Tests/SeekTest.php',
                'testtable' => '/ludoDB/Tests/TestTable.php',
                'timecontrol' => '/TimeControl.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    }
);
// @codeCoverageIgnoreEnd